// Shared plan limits — no "use client" so this can be imported by both
// React client components (plans.ts) and server API routes (generate/route.ts).
// This is the SINGLE SOURCE OF TRUTH for per-plan limits.
// Prices here must stay in sync with src/lib/pricing.ts.

export const PLAN_CONFIG = {
  starter: {
    price: 95,
    channels: 1,
    bookingsPerMonth: 50,
    customDomains: 0,
    websites: 0,
    voiceMinutes: 150,
    textMessages: 500,
    teamMembers: 1,
    multiLocation: 0,
    voiceAgent: false,
    analytics: false,
    followUps: false,
    whiteLabel: false,
    aiTraining: "generic" as const,
    support: "email" as const,
  },
  pro: {
    price: 295,
    channels: 3,
    bookingsPerMonth: Infinity,
    customDomains: 1,
    websites: 1,
    voiceMinutes: 650,
    textMessages: Infinity,
    teamMembers: 3,
    multiLocation: 2,
    voiceAgent: true,
    analytics: true,
    followUps: true,
    whiteLabel: true,
    aiTraining: "custom" as const,
    support: "liveChat" as const,
  },
  premium: {
    price: 595,
    channels: 3,
    bookingsPerMonth: Infinity,
    customDomains: 3,
    websites: 3,
    voiceMinutes: 1300,
    textMessages: Infinity,
    teamMembers: Infinity,
    multiLocation: Infinity,
    voiceAgent: true,
    analytics: true,
    followUps: true,
    whiteLabel: true,
    aiTraining: "advanced" as const,
    support: "dedicated" as const,
  },
  custom: {
    price: 1500,
    channels: Infinity,
    bookingsPerMonth: Infinity,
    customDomains: Infinity,
    websites: Infinity,
    voiceMinutes: Infinity,
    textMessages: Infinity,
    teamMembers: Infinity,
    multiLocation: Infinity,
    voiceAgent: true,
    analytics: true,
    followUps: true,
    whiteLabel: true,
    aiTraining: "advanced" as const,
    support: "dedicated" as const,
  },
} as const;

export type PlanId = keyof typeof PLAN_CONFIG;
