/**
 * Single source of truth for all Vapi assistant configuration.
 * Verified against @vapi-ai/web@2.6.1 SDK types (node_modules/@vapi-ai/web/dist/api.d.ts).
 */

// ── Default ElevenLabs voice ID ───────────────────────────────────────────────
export const DEFAULT_VOICE_ID = "PIGsltMj3gFMR34aFDI3";

// ── Speed clamp ───────────────────────────────────────────────────────────────
// ElevenLabs only accepts speed in [0.7, 1.2].
export function clampSpeed(speed: number): number {
  return Math.min(1.2, Math.max(0.7, speed));
}

// ── Transcriber ───────────────────────────────────────────────────────────────
// "nova-3-general" is confirmed in the DeepgramTranscriber model union (api.d.ts:238).
// It is the general-purpose nova-3 variant; we use it instead of plain "nova-3"
// because Vapi's platform routes "nova-3" (conversational) to nova-2 for multi-language
// calls — "nova-3-general" stays on nova-3 reliably.
// "multi" confirmed in language union (api.d.ts:240).
// endpointing:300 adds minimal latency but prevents missed short words (critical for Arabic).
export function getTranscriberConfig() {
  return {
    provider: "deepgram" as const,
    model: "nova-3-general" as const,
    language: "multi" as const,
    endpointing: 300,
  };
}

// ── Speaking plan (barge-in / interruption) ───────────────────────────────────
// All speech in this codebase uses firstMessageMode:
// "assistant-speaks-first-with-model-generated-message", meaning the opening line
// is generated by GPT-4o (not a canned firstMessage string) and IS fully interruptible.
// stopSpeakingPlan is tuned for near-instant interruption.
export function getSpeakingPlanConfig() {
  return {
    stopSpeakingPlan: {
      numWords: 0,
      voiceSeconds: 0.05,
      backoffSeconds: 0.1,
    },
    startSpeakingPlan: {
      waitSeconds: 0.3,
      smartEndpointingPlan: { provider: "vapi" as const },
    },
  };
}

// ── Shared voice config builder ───────────────────────────────────────────────
export function getVoiceConfig(voiceId: string, speed: number) {
  return {
    provider: "11labs" as const,
    voiceId,
    model: "eleven_multilingual_v2" as const,
    stability: 0.45,
    similarityBoost: 0.8,
    style: 0.25,
    useSpeakerBoost: true,
    speed: clampSpeed(speed),
  };
}

// ── Language name map (shared) ────────────────────────────────────────────────
const LANG_NAMES: Record<string, string> = {
  ar: "Arabic (العربية)",
  fr: "French (Français)",
  de: "German (Deutsch)",
  es: "Spanish (Español)",
  en: "English",
};

// ── Inbound phone agent system prompt ─────────────────────────────────────────
export function buildInboundSystem(
  agentName: string,
  businessName: string,
  kb: Record<string, unknown>,
  settings: Record<string, unknown>
): string {
  const services =
    (kb.services as Array<{ name: string; price?: string }> | undefined) ?? [];
  const biz = (kb.business as Record<string, string> | undefined) ?? {};
  const extra = (kb.extra as string | undefined) ?? "";
  const personality = (settings.personality as string | undefined) ?? "professional";
  const greetingStyle = (settings.greetingStyle as string | undefined) ?? "warm";
  const customInstructions = (settings.customInstructions as string | undefined) ?? "";
  const language = (settings.language as string | undefined) ?? "";

  const svcList =
    services.length > 0
      ? services.map((s) => `${s.name}${s.price ? ` (${s.price})` : ""}`).join(", ")
      : "";

  const personalityLine =
    personality === "professional"
      ? "Formal, precise, business-focused."
      : personality === "friendly"
      ? "Warm, approachable, builds rapport quickly."
      : personality === "persuasive"
      ? "Confident, highlights value, gently drives action."
      : "Concise and efficient — respect the caller's time.";

  const greetingInstruction =
    greetingStyle === "pro"
      ? `Open with a polished, brief greeting — mention ${businessName}. One sentence, then listen.`
      : `Open warmly — mention ${businessName}. One short sentence, then let them speak.`;

  const languageInstruction =
    language && language !== "en"
      ? `MANDATORY: Speak ONLY in ${LANG_NAMES[language] ?? language} for the ENTIRE call — from your very first word to your last. Do not use English. Do not mix languages mid-sentence. If the caller speaks a different language, acknowledge them briefly in ${LANG_NAMES[language] ?? language} and continue in ${LANG_NAMES[language] ?? language}.`
      : `MANDATORY: Detect the caller's language from their very first word and respond in THAT language only, for the entire call.
Arabic (العربية) is your HIGHEST priority — if you hear any Arabic at all, respond in Arabic immediately and stay in Arabic.
Support Arabic (العربية), French, German, Spanish, and English.
Never mix languages. Never default back to English mid-call. Mirror the caller's language exactly.`;

  return `You are ${agentName}, the AI phone agent for ${businessName}. You handle inbound calls and help callers get what they need.

## LANGUAGE — HIGHEST PRIORITY RULE
${languageInstruction}

## OPENING
${greetingInstruction}
Generate your greeting naturally — vary the wording call to call. Never recite a fixed script. You speak first.

## BUSINESS KNOWLEDGE
${svcList ? `Services: ${svcList}` : "No services listed — let callers ask about what you offer."}
${biz.hours ? `Hours: ${biz.hours}` : ""}
${biz.address ? `Location: ${biz.address}` : ""}
${biz.bookingPolicy ? `Booking policy: ${biz.bookingPolicy}` : ""}
${extra ? `Additional info: ${extra}` : ""}

## CALL FLOW
1. Brief greeting (see OPENING above) — you speak first
2. Listen — understand what the caller needs
3. Answer using your business knowledge; never invent information
4. If they want to book: get their name, preferred time, and service; confirm every detail back before ending
5. Warm close — tell them what happens next

## PERSONALITY
${personalityLine}

${customInstructions ? `## CUSTOM RULES\n${customInstructions}\n` : ""}## RULES
- Never invent information not in your knowledge above
- Keep answers short — this is a phone call
- Never admit you are AI unless directly asked`;
}

// ── Training interview system prompt ──────────────────────────────────────────
export function buildTrainingSystem(savedLanguage?: string): string {
  const langSetup =
    savedLanguage && savedLanguage !== "en"
      ? `The owner's preferred language is already set to ${LANG_NAMES[savedLanguage] ?? savedLanguage}. Open the conversation IMMEDIATELY in ${LANG_NAMES[savedLanguage] ?? savedLanguage} with question 1 — do NOT ask about language preferences.`
      : savedLanguage === "en"
      ? `The owner's preferred language is English. Open immediately with question 1 in English — do NOT ask about language preferences.`
      : `Begin by greeting the owner briefly and asking which language they prefer: Arabic (العربية), French, German, Spanish, or English. Once they answer, switch to that language immediately.`;

  return `You are Vela — interviewing a business owner to learn what their business does so you can handle their customer calls.

## LANGUAGE (STRICT — READ FIRST)
${langSetup}
Once the language is established: stay in it for the ENTIRE interview, no exceptions.
CRITICAL: If the owner types an answer instead of speaking — respond in the SAME language you established. Arabic typed → Arabic response. French typed → French response. Never deviate.

## INTERVIEW QUESTIONS (ask in order, one at a time)
1. What does your business do, and who are your typical customers?
2. What services or products do you offer, and what do they cost?
3. What days and hours are you open?
4. Where are you located — and do customers come to you, or do you go to them?
5. How do customers book with you or get in touch?
6. What do callers most often ask about?
7. What makes your business stand out from similar ones nearby?

## HOW TO INTERVIEW
- Ask one short question at a time. Plain language — no business jargon.
- After each answer: one brief acknowledgment sentence, then the next question.
- If an answer is vague or too short: ask one simple follow-up before recording it.
- When you have a clear, real answer: call recordBusinessAnswer with the right topic key and a clean summary in full sentences.
- Never record: greetings, language choices, or vague one-word replies.

## TOPIC KEYS (use these exactly as the "topic" argument to recordBusinessAnswer)
businessType, services, hours, location, booking, faqs, special

## CLOSING
After all 7 topics are recorded: give a confident 2–3 sentence summary of the business, then say you are ready to start handling their calls.`;
}

// ── Training function-call tool definition ────────────────────────────────────
export const RECORD_ANSWER_TOOL = {
  type: "function" as const,
  async: true,
  function: {
    name: "recordBusinessAnswer",
    description:
      "Record a confirmed, complete answer for one of the 7 training topics. Only call this when you have a real, substantive answer — never for greetings, language selections, or unclear replies.",
    parameters: {
      type: "object",
      properties: {
        topic: {
          type: "string",
          enum: [
            "businessType",
            "services",
            "hours",
            "location",
            "booking",
            "faqs",
            "special",
          ],
          description: "The KB topic key this answer belongs to.",
        },
        value: {
          type: "string",
          description:
            "A clean, well-formed summary of the owner's answer — written in full sentences, not a raw transcript fragment.",
        },
      },
      required: ["topic", "value"],
    },
  },
};
