/**
 * Single source of truth for all Vapi assistant configuration.
 * Verified against @vapi-ai/web@2.6.1 SDK types (node_modules/@vapi-ai/web/dist/api.d.ts).
 */

// ── Centralized voice list ────────────────────────────────────────────────────
export interface VoiceEntry {
  id: string;
  name: string;
  description: string;
  gender: "male" | "female";
}

export const VOICES: VoiceEntry[] = [
  // Male
  { id: "Qrl71rx6Yg8RvyPYRGCQ", name: "Théo",      description: "Warm and expressive, natural ease",          gender: "male" },
  { id: "HKFOb9iktHA85uKXydRT", name: "Mateo",     description: "Smooth and confident, clear delivery",       gender: "male" },
  { id: "Czw3Dn181ypdrCOnPfif", name: "Felix",     description: "Crisp and measured, calm authority",         gender: "male" },
  { id: "TUKJhQmz3RPYBNAgC5A1", name: "Miles",     description: "Natural and grounded, easy to trust",        gender: "male" },
  { id: "DANw8bnAVbjDEHwZIoYa", name: "Sami",      description: "Deep and resonant, commanding presence",     gender: "male" },
  // Female
  { id: "Qggl4b0xRMiqOwhPtVWT", name: "Céline",    description: "Warm and articulate, engaging tone",         gender: "female" },
  { id: "FvmvwvObRqIHojkEGh5N", name: "Valentina", description: "Bright and confident, effortlessly clear",   gender: "female" },
  { id: "22VndfJPBU7AZORAZZTT", name: "Hanna",     description: "Precise and composed, professional warmth",  gender: "female" },
  { id: "iFSsEDGbm0FiEd2IVH4w", name: "Ava",       description: "Friendly and natural, easy to listen to",    gender: "female" },
  { id: "u0TsaWvt0v8migutHM3M", name: "Nour",      description: "Smooth and expressive, balanced tone",       gender: "female" },
];

// ── Default ElevenLabs voice ID (Miles — English male) ────────────────────────
export const DEFAULT_VOICE_ID = "TUKJhQmz3RPYBNAgC5A1";

// ── Language-aware default — only used when NO voice is explicitly saved ──────
// Owner's explicit choice always wins. This only applies when voiceId is absent.
export function getDefaultVoiceId(language?: string): string {
  return language === "ar" ? "DANw8bnAVbjDEHwZIoYa" : DEFAULT_VOICE_ID;
}

// ── Call duration limits ──────────────────────────────────────────────────────
// Verified from @vapi-ai/web api.d.ts CreateAssistantDTO + AssistantOverrides:
//   maxDurationSeconds — @default 600 (10 min), @min 10, @max 43200
//   silenceTimeoutSeconds — NOT present on CreateAssistantDTO / AssistantOverrides;
//     it exists only on the transfer sub-assistant type and cannot be set here.
// Root cause of mid-call ejections: Vapi's 600s default was never overridden,
// so any call over 10 minutes was terminated with {"type":"ejected","msg":"Meeting has ended"}.
export const CALL_LIMITS = {
  maxDurationSeconds: 1800,  // 30 minutes
} as const;

// ── Speed clamp ───────────────────────────────────────────────────────────────
// ElevenLabs only accepts speed in [0.7, 1.2].
export function clampSpeed(speed: number): number {
  return Math.min(1.2, Math.max(0.7, speed));
}

// ── Transcriber ───────────────────────────────────────────────────────────────
// Using ElevenLabs Scribe — the only transcriber in Vapi's stack that supports
// Arabic. Deepgram (nova-2, nova-3, nova-3-general) all reject "ar" at runtime.
//
// Verified from @vapi-ai/web api.d.ts lines 317-325:
//   interface ElevenLabsTranscriber {
//     provider: "11labs";
//     model?: "scribe_v1";        ← only valid model value
//     language?: "ar" | "en" | "fr" | "de" | "es" | ...;  ← ISO 639-1
//     fallbackPlan?: ...;
//   }
//   "ar" is an explicit valid value. No Deepgram-style endpointing field.
//
// Language mapping (app stores "ar"/"en"/"fr"/"de"/"es"/""):
//   ar → "ar"  en → "en"  fr → "fr"  de → "de"  es → "es"
//   unknown / empty → "en" (English fallback, per product requirement)
//
// Input is trim+lowercase so "AR", " ar ", etc. all resolve correctly.
// Any unrecognised value falls back to "en" — no invalid string can reach Vapi.
type ScribeLang = "ar" | "en" | "fr" | "de" | "es";

const SCRIBE_LANG_MAP: Partial<Record<string, ScribeLang>> = {
  ar: "ar", en: "en", fr: "fr", de: "de", es: "es",
};

export function getTranscriberConfig(language?: string): {
  provider: "11labs";
  model: "scribe_v1";
  language: ScribeLang;
} {
  const normalized = (language ?? "").trim().toLowerCase();
  const lang: ScribeLang = SCRIBE_LANG_MAP[normalized] ?? "en";
  return {
    provider: "11labs" as const,
    model: "scribe_v1" as const,
    language: lang,
  };
}

// ── Speaking plan (barge-in / interruption) ───────────────────────────────────
// All speech in this codebase uses firstMessageMode:
// "assistant-speaks-first-with-model-generated-message", meaning the opening line
// is generated by GPT-4o (not a canned firstMessage string) and IS fully interruptible.
// stopSpeakingPlan is tuned for near-instant interruption.
export function getSpeakingPlanConfig() {
  return {
    stopSpeakingPlan: {
      numWords: 0,
      voiceSeconds: 0.05,
      backoffSeconds: 0.1,
    },
    startSpeakingPlan: {
      waitSeconds: 0.3,
      smartEndpointingPlan: { provider: "vapi" as const },
    },
  };
}

// ── Shared voice config builder ───────────────────────────────────────────────
// voiceId is always used as-is — the language-aware default is applied BEFORE
// calling this function (via getDefaultVoiceId). Owner's explicit choice wins.
export function getVoiceConfig(voiceId: string, speed: number) {
  return {
    provider: "11labs" as const,
    voiceId,
    model: "eleven_multilingual_v2" as const,
    stability: 0.45,
    similarityBoost: 0.8,
    style: 0.25,
    useSpeakerBoost: true,
    speed: clampSpeed(speed),
  };
}

// ── Language name map (shared) ────────────────────────────────────────────────
const LANG_NAMES: Record<string, string> = {
  ar: "Arabic (العربية)",
  fr: "French (Français)",
  de: "German (Deutsch)",
  es: "Spanish (Español)",
  en: "English",
};

// ── Inbound phone agent system prompt ─────────────────────────────────────────
export function buildInboundSystem(
  agentName: string,
  businessName: string,
  kb: Record<string, unknown>,
  settings: Record<string, unknown>
): string {
  const services =
    (kb.services as Array<{ name: string; price?: string }> | undefined) ?? [];
  const biz = (kb.business as Record<string, string> | undefined) ?? {};
  const extra = (kb.extra as string | undefined) ?? "";
  const personality = (settings.personality as string | undefined) ?? "professional";
  const greetingStyle = (settings.greetingStyle as string | undefined) ?? "warm";
  const customInstructions = (settings.customInstructions as string | undefined) ?? "";
  const language = (settings.language as string | undefined) ?? "";

  const svcList =
    services.length > 0
      ? services.map((s) => `${s.name}${s.price ? ` (${s.price})` : ""}`).join(", ")
      : "";

  const personalityLine =
    personality === "professional"
      ? "Formal, precise, business-focused."
      : personality === "friendly"
      ? "Warm, approachable, builds rapport quickly."
      : personality === "persuasive"
      ? "Confident, highlights value, gently drives action."
      : "Concise and efficient — respect the caller's time.";

  const greetingInstruction =
    greetingStyle === "pro"
      ? `Open with a polished, brief greeting — mention ${businessName}. One sentence, then listen.`
      : `Open warmly — mention ${businessName}. One short sentence, then let them speak.`;

  const languageInstruction =
    language && language !== "en"
      ? `MANDATORY: Speak ONLY in ${LANG_NAMES[language] ?? language} for the ENTIRE call — from your very first word to your last. Do not use English. Do not mix languages mid-sentence. If the caller speaks a different language, acknowledge them briefly in ${LANG_NAMES[language] ?? language} and continue in ${LANG_NAMES[language] ?? language}.`
      : `MANDATORY: Detect the caller's language from their very first word and respond in THAT language only, for the entire call.
Arabic (العربية) is your HIGHEST priority — if you hear any Arabic at all, respond in Arabic immediately and stay in Arabic.
Support Arabic (العربية), French, German, Spanish, and English.
Never mix languages. Never default back to English mid-call. Mirror the caller's language exactly.`;

  return `You are ${agentName}, the AI phone agent for ${businessName}. You handle inbound calls and help callers get what they need.

## LANGUAGE — HIGHEST PRIORITY RULE
${languageInstruction}

## OPENING
${greetingInstruction}
Generate your greeting naturally. Vary your exact wording every call — never open with the same phrase twice, and never use a fixed word like "مرحبا" or "Hello" as a rote opener. You speak first.

## BUSINESS KNOWLEDGE
${svcList ? `Services: ${svcList}` : "No services listed — let callers ask about what you offer."}
${biz.hours ? `Hours: ${biz.hours}` : ""}
${biz.address ? `Location: ${biz.address}` : ""}
${biz.bookingPolicy ? `Booking policy: ${biz.bookingPolicy}` : ""}
${extra ? `Additional info: ${extra}` : ""}

## CALL FLOW
1. Brief greeting (see OPENING above) — you speak first
2. Listen — understand what the caller needs
3. Answer using your business knowledge; never invent information
4. If they want to book: get their name, preferred time, and service; confirm every detail back before ending
5. Warm close — tell them what happens next

## PERSONALITY
${personalityLine}

${customInstructions ? `## CUSTOM RULES\n${customInstructions}\n` : ""}## RULES
- Never invent information not in your knowledge above
- Keep answers short — this is a phone call
- Never admit you are AI unless directly asked`;
}

// ── Training interview system prompt ──────────────────────────────────────────
export function buildTrainingSystem(savedLanguage?: string): string {
  const langSetup =
    savedLanguage === "ar"
      ? `The owner's preferred language is Arabic (العربية). Open IMMEDIATELY in Arabic with question 1. Do NOT say "مرحبا" — use a varied, natural Arabic opener or go straight to your first question. Never open the same way twice.`
    : savedLanguage && savedLanguage !== "en"
      ? `The owner's preferred language is already set to ${LANG_NAMES[savedLanguage] ?? savedLanguage}. Open IMMEDIATELY in ${LANG_NAMES[savedLanguage] ?? savedLanguage} with question 1 — do NOT ask about language preferences. Vary your opening — never open with the same phrase twice.`
    : savedLanguage === "en"
      ? `The owner's preferred language is English. Open immediately with question 1 in English — do NOT ask about language preferences.`
      : `Detect the owner's language from their very first words — do NOT ask which language they prefer.
Arabic (العربية) is your HIGHEST priority: if you hear or read any Arabic at all — even a single word — respond in Arabic IMMEDIATELY and stay in Arabic for the entire interview.
IMPORTANT: If the transcription reads "Arabia" or "Arabia Arabia" — that is a speech-to-text artifact for the Arabic word "عربي" — treat it as Arabic and switch to Arabic immediately.
Supported languages: Arabic (العربية), French (Français), German (Deutsch), Spanish (Español), English. Match the owner's language from their very first message.`;

  return `You are Vela — interviewing a business owner to build their AI knowledge base so you can handle their customer calls. Keep it conversational and quick. One question at a time.

## LANGUAGE (STRICT — READ FIRST)
${langSetup}
Once the language is established: stay in it for the ENTIRE interview, no exceptions.
IMPORTANT: Topic keys (businessType, services, hours, location, booking, faqs, special) are internal identifiers only — ask all questions and give all responses in the established language.
CRITICAL: If the owner types an answer instead of speaking — respond in the SAME language. Arabic typed → Arabic response. French typed → French response. Never deviate.

## INTERVIEW QUESTIONS (ask in this exact order, one at a time)
Keep each question short — no more than 10 words. Do not include examples in the question. If an answer is vague, ask ONE brief follow-up with a short example, then move on.

1. Business type — Ask: "What does your business do?"

2. Services — Ask: "What services do you offer?"

3. Prices — Ask: "What do your services cost?"

4. Hours — Ask: "What days and hours are you open?"

5. Location — Ask: "Where are you located?"

6. Booking — Ask: "How do customers book with you?"

7. Unique selling point — Ask: "What makes your business stand out?"

## VALIDATION — apply before calling recordBusinessAnswer
VALID — record immediately:
- businessType: any description of what the business does
- services: at least one service name mentioned (price can be a range like "100k–500k" or omitted)
- hours: any days or times in any form ("mon-fri", "9 to 5", "every day")
- location: any location info including "we go to clients" or "online only"
- booking: any booking method including "just call us" or "no appointment needed"
- faqs: at least one question or topic mentioned by the owner
- special: any differentiator, even short

NON-ANSWERS — do NOT record; ask the same question again with a different example:
Greetings only ("hi", "hello", "yes", "ok", "fine"), pure negatives ("no", "nothing", "I don't know"), or vague non-info ("a lot", "everything", "it depends", "the best", "rich people").

VAGUE but not empty — ask ONE short follow-up with a brief example, then accept their next answer:
"We do everything" → "Like what — haircut, massage, consultation?"
"We're open most days" → "What hours — like 9am to 6pm?"

## NORMALIZATION — always store the clean version, never raw transcript
Hours: convert to standard format before storing.
  "mon to sat 9 to 5" → "Mon–Sat 9:00–17:00"
  "every day 8am to 8pm" → "Daily 8:00–20:00"
  "sunday to thursday 10am to 7pm and friday 10 to 2" → "Sun–Thu 10:00–19:00, Fri 10:00–14:00"
Service names: capitalize. Prices: keep as stated — ranges fine.
FAQs: write each as a clean full-sentence Q&A.

## TOPIC KEYS (use these exactly as the "topic" argument to recordBusinessAnswer)
businessType, services, hours, location, booking, faqs, special

## CLOSING
After all 7 topics are recorded: give a confident 2–3 sentence summary of the business using NORMALIZED data, then say you are ready to start handling their calls.`;
}

// ── Training function-call tool definition ────────────────────────────────────
export const RECORD_ANSWER_TOOL = {
  type: "function" as const,
  async: true,
  function: {
    name: "recordBusinessAnswer",
    description:
      "Record a confirmed, complete answer for one training topic. ONLY call this when you have a real, substantive answer — never for greetings, single-word replies, or vague non-info like 'a lot' or 'I don't know'. Always store the NORMALIZED version: hours as 'Mon–Sat 9:00–17:00', service names capitalized, Q&A written in full sentences.",
    parameters: {
      type: "object",
      properties: {
        topic: {
          type: "string",
          enum: [
            "businessType",
            "services",
            "hours",
            "location",
            "booking",
            "faqs",
            "special",
          ],
          description: "The KB topic key this answer belongs to.",
        },
        value: {
          type: "string",
          description:
            "The NORMALIZED, clean summary — not raw transcript. Hours must be in 'Mon–Sat 9:00–17:00' format. Service names must be capitalized. FAQs as full-sentence Q&A pairs. Prices as stated (ranges fine).",
        },
      },
      required: ["topic", "value"],
    },
  },
};
