// Bilingual business-type list for the landing page's moving strip
// (BusinessTypesStrip.tsx). Starts from the same categories the real
// business detector already uses (src/app/auth/signup/page.tsx's
// BUSINESS_CATEGORIES / detectBusinessType), expanded well past 50 --
// this file is landing-page-only decorative copy, not wired into the
// detector itself, so auth/signup logic is untouched.
export const BUSINESS_TYPES: { en: string; ar: string }[] = [
  { en: "Dental clinics", ar: "عيادات الأسنان" },
  { en: "Gyms", ar: "الصالات الرياضية" },
  { en: "Salons", ar: "صالونات التجميل" },
  { en: "Barbershops", ar: "صالونات الحلاقة" },
  { en: "Real estate", ar: "العقارات" },
  { en: "Restaurants", ar: "المطاعم" },
  { en: "Cafes", ar: "المقاهي" },
  { en: "Law firms", ar: "مكاتب المحاماة" },
  { en: "Car rentals", ar: "تأجير السيارات" },
  { en: "Garages", ar: "ورش السيارات" },
  { en: "Spas", ar: "السبا" },
  { en: "Beauty centers", ar: "مراكز التجميل" },
  { en: "Pharmacies", ar: "الصيدليات" },
  { en: "Medical clinics", ar: "العيادات الطبية" },
  { en: "Physiotherapy", ar: "العلاج الطبيعي" },
  { en: "Veterinary clinics", ar: "العيادات البيطرية" },
  { en: "Hotels", ar: "الفنادق" },
  { en: "Travel agencies", ar: "وكالات السفر" },
  { en: "Driving schools", ar: "مدارس تعليم القيادة" },
  { en: "Tutoring centers", ar: "مراكز التقوية" },
  { en: "Interior design", ar: "التصميم الداخلي" },
  { en: "Photography studios", ar: "استوديوهات التصوير" },
  { en: "Event planners", ar: "منظمو الفعاليات" },
  { en: "Wedding venues", ar: "قاعات الأفراح" },
  { en: "Florists", ar: "محلات الزهور" },
  { en: "Bakeries", ar: "المخابز" },
  { en: "Laundries", ar: "المغاسل" },
  { en: "Cleaning services", ar: "خدمات التنظيف" },
  { en: "Pet grooming", ar: "تجميل الحيوانات الأليفة" },
  { en: "Fitness studios", ar: "استوديوهات اللياقة" },
  { en: "Yoga studios", ar: "استوديوهات اليوغا" },
  { en: "Dermatology clinics", ar: "عيادات الجلدية" },
  { en: "Eye clinics", ar: "عيادات العيون" },
  { en: "Medical labs", ar: "المختبرات الطبية" },
  { en: "Insurance agencies", ar: "وكالات التأمين" },
  { en: "Real estate developers", ar: "مطورو العقارات" },
  { en: "Furniture stores", ar: "محلات الأثاث" },
  { en: "Electronics stores", ar: "محلات الإلكترونيات" },
  { en: "Fashion boutiques", ar: "بوتيكات الأزياء" },
  { en: "Jewelry stores", ar: "محلات المجوهرات" },
  { en: "Perfume shops", ar: "محلات العطور" },
  { en: "Marketing agencies", ar: "وكالات التسويق" },
  { en: "IT services", ar: "خدمات تقنية المعلومات" },
  { en: "Coworking spaces", ar: "مساحات العمل المشترك" },
  { en: "Car dealers", ar: "معارض السيارات" },
  { en: "Tire shops", ar: "محلات الإطارات" },
  { en: "Plumbers", ar: "السباكون" },
  { en: "Electricians", ar: "الكهربائيون" },
  { en: "AC maintenance", ar: "صيانة التكييف" },
  { en: "Moving companies", ar: "شركات النقل" },
  { en: "Schools", ar: "المدارس" },
  { en: "Nurseries", ar: "الحضانات" },
  { en: "Accounting firms", ar: "مكاتب المحاسبة" },
  { en: "Recruitment agencies", ar: "وكالات التوظيف" },
  { en: "Construction companies", ar: "شركات المقاولات" },
];
